[build]
  # 構建設定
  publish = "."
  command = "node build-for-netlify.js"
  functions = "netlify/functions"

[build.environment]
  # 環境變數
  NODE_VERSION = "18"
  # 配置秘密掃描
  SECRETS_SCAN_ENABLED = "false"
  # Notion API 密鑰
  NOTION_API_KEY = "secret_iSDhSCT8HPZMjPsX8YuMdhfzPJ2EYJrfXLdE17L88cV"

# 秘密掃描配置
[build.secrets_scan]
  enabled = false

# 或者使用路徑排除（如果需要啟用掃描但排除特定路徑）
# [build.secrets_scan]
#   enabled = true
#   omit_paths = [
#     "data/**",
#     "docs/**", 
#     "scripts/**",
#     "pages/**",
#     "assets/js/**",
#     "*.md",
#     "*.csv",
#     "test-*",
#     "debug-*",
#     ".netlify/**"
#   ]

[[headers]]
  # 設定所有頁面的安全標頭
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  # 強制 HTTPS
  from = "http://tanawat-order-system.netlify.app/*"
  to = "https://tanawat-order-system.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  # 靜態資源快取
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  [redirects.conditions]
    max-age = "31536000"

[[redirects]]
  # SPA 路由支援 - 將所有路徑重定向到 index.html
  from = "/*"
  to = "/index.html"
  status = 200

# 表單處理設定（如果需要）
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

# 函數設定（如果使用 Netlify Functions）
[functions]
  directory = "netlify/functions"

# API 重定向配置
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 注意：邊緣函數設定已移除，因為目前不使用 edge functions
